### ISSUE TITLE
Details page: Model details statuses aren't coloured

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#133]
<img width="267" alt="Screen Shot 2019-10-30 at 4 35 56 PM" src="https://user-images.githubusercontent.com/532033/67904246-63eea980-fb33-11e9-953b-4d83d5897460.png">

**Comment by barrymcgee** [comment]
@spencerbygraves Only Block/Alert/Running have colors in the designs - what color should the dot icon be for;

- Waiting
- Unknown
- Active

**Comment by cristinadresch** [comment]
@hatched @barrymcgee do we have a list of all statuses? It just sounds like we missed those 3, want to make sure we don't forget any others.

So at the moment we have:
- Blocked - red
- Alert - yellow
- Running - grey

--

I would suggest for the 3 new ones. @spencerbygraves @clagom what do you think? Let's make sure this waits until Monday so we all agree.

- Waiting - no icon, just text since technically the state hasn't been defined
- Unknown - no icon, just text since technically the state hasn't been defined
- Active - grey (same as running)

**Comment by spencerbygraves** [comment]
For reference, this is what I currently have in the designs.

I have Waiting as yellow, as I assume it's close to pending, which has previously been yellow.

Maintenance is not mentioned above, this is also yellow at the moment.

I didn't have Unknown in the designs. This could either have no icon as @cristinadresch suggests, or perhaps an empty circle?

![image](https://user-images.githubusercontent.com/9105999/68019962-083c3180-fc95-11e9-8f5d-55b048796793.png)

**Comment by hatched** [comment]
I feel like we should always have an icon else it'll look weird.

Here are some references for the possible values across the different entities:
https://discourse.jujucharms.com/t/charm-unit-status-and-their-meanings/1168
https://github.com/juju/juju/blob/a436632538c64ed76a394d8692b091a0d129ea2d/core/status/status.go#L52
