### ISSUE TITLE
Jaas menu - external link icons are cut off

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/jaas-dashboard#230]
In the Jaas menu the external link icons are cut off:

![image](https://user-images.githubusercontent.com/9105999/69357470-0d314700-0c7d-11ea-95ea-c3ed74c1bbc1.png)

**Comment by barrymcgee** [comment]
Doesn't appear to be a Vanilla bug, but we're not adding any override styles on this? 🧐

https://codepen.io/barrymcgee/pen/YzzMEZW

**Comment by barrymcgee** [comment]
Turns out this is a Vanilla bug.

It was being caused by all links in the sidebar being assigned `display: flex`in this project. 

Trying to isolate this bug in Vanilla I discovered it's resolved in the latest release of Vanilla - `2.5.0`

This project currently uses `2.4.1` so the fix is to upgrade Vanilla.
