### ISSUE TITLE
JAAS dashboard - are more models loading in the background?

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#295]
At the moment it's impossible to understand if the dashboard is loading more models or not. There are models that are really slow to load, and they just appear suddenly when done. We do have designs and explorations for different loading statuses, can we indicate it to the users?

**Comment by hatched** [comment]
No not really. There is only every 30s per loop when we're not actively fetching statuses from models. So any global 'fetching model status' indicator would be active for the majority of the time. With the new Juju updates model statuses will be much faster and the upcoming JAAS updates will mean that the polling will go away and so will those delays which is why we decided against implementing any of the model level loading statuses already.
