### ISSUE TITLE
Topology not responsive

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/jaas-dashboard#325]
@hatched maybe you are aware, but with the responsive breaking point the topology should shrink:

![Screenshot 2020-01-30 at 13.47.09.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/bd41c48d-af7d-45b2-a263-3f74bc6549a0)

**Comment by hatched** [comment]
Some investigation is needed to find the best solution to this problem:

- The topology requires hard coded `width` and `height` coordinates now so that it can render the icons in the correct locations.
- The width adjust on that sidebar is done via CSS so there isn't a way to easily update the width of the topology depending on the width of the element.

**Comment by cristinadresch** [comment]
@anthonydillon do you think you'll be able to work on it this week?

**Comment by cristinadresch** [comment]
@anthonydillon @hatched nice!! 🥳
