### ISSUE TITLE
Error count number is off centre

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#425]
![Screen Shot 2020-04-14 at 2.07.20 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/72fb88d0-d9e1-4a17-a062-eed838fb7bdf)

**Comment by barrymcgee** [comment]
This is simply text, text-aligned to the center, in a box. 

It may look off-centre because certain numbers, like `4`, are not symmetrical. 

<img width="374" alt="Screenshot 2020-04-15 at 11 57 10" src="https://user-images.githubusercontent.com/505570/79329800-52962f80-7f10-11ea-8784-7a02ef11fae7.png">
<img width="732" alt="Screenshot 2020-04-15 at 11 57 19" src="https://user-images.githubusercontent.com/505570/79329804-53c75c80-7f10-11ea-9547-c791ca686589.png">

Change the number to a symmetrical number like `8` and you'll see it looks more centred.

<img width="387" alt="Screenshot 2020-04-15 at 12 00 50" src="https://user-images.githubusercontent.com/505570/79330311-39da4980-7f11-11ea-86e1-c8241417bccb.png">

To disguise this disparity, we'd either need to vastly increase the padding between the number or decrease the font-size - both of which are incompatible with the current design.

**Comment by hatched** [comment]
I think the issue is that you're seeing it on a high res screen whereas mine aren't.

![Screen Shot 2020-04-15 at 9 42 12 AM](https://user-images.githubusercontent.com/532033/79357536-6be1b080-7efd-11ea-8c0e-45b44cb01e22.png)
![Screen Shot 2020-04-15 at 9 42 20 AM](https://user-images.githubusercontent.com/532033/79357539-6c7a4700-7efd-11ea-94c1-4fb789d50661.png)

**Comment by hatched** [comment]
After doing some further investigation on this there appears to be a difference between the browsers in how this is rendered. It's likely that there just isn't enough pixels so the difference between the browsers rendering engines is more obvious.

@spencerbygraves can you take a look at alternate designs here to give us a bit more wiggle room to allow for the differences in browser renderings?

**Comment by spencerbygraves** [comment]
We have the [labels in Vanilla](https://vanillaframework.io/docs/patterns/labels#deprecated), but these have specific meaning for docs and may need extending for status. I think we would need to discuss that with @clagom and the Vanilla team.

As you can see, the red label is "Deprecated" and not currently for "errors"

![image](https://user-images.githubusercontent.com/9105999/82901212-8a53b680-9f55-11ea-922b-55ecea2494ad.png)

**Comment by spencerbygraves** [comment]
Closing this as the conversation has moved to label design, which is being looked at [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/3126).
