### ISSUE TITLE
Reduce controller column width.

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#426]
We're giving too much width to the controller column that doesn't require it. It can be shrunk and that space given to the name column (on all 3 groups). This will also give more room for the error message.

![Screen Shot 2020-04-14 at 2.20.36 PM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/62f57efa-7468-408d-bfda-bc31200ec991)

**Comment by clagom** [comment]
+1.
@spencerbygraves has nice spacing in his design as a reference

**Comment by barrymcgee** [comment]
What's the maximum possible character length of a controller name?

**Comment by clagom** [comment]
> What's the maximum possible character length of a controller name?
There's no way we can always include a controller name entirely and it's hard to know because users give name, so we don't know.
An example, when a controller name is used in flat-hierarchy environment but trying to give hierarchy via tis name:
<img width="353" alt="Screenshot 2020-04-15 at 15 21 16" src="https://user-images.githubusercontent.com/1953388/79348324-c5ad9f00-7f2c-11ea-8446-fcf3ee71260a.png">
