### ISSUE TITLE
cannot view a model consuming a CMR

### ISSUE THREAD

**Issue by mitechie** [canonical-web-and-design/jaas-dashboard#526]
**Describe the bug**
I have a CMR in a controller and the offering side is ok, but the consuming side won't load and I got a nice helpful link to file a bug here

**To Reproduce**

juju add-model keystone-backend
juju deploy (https://pastebin.canonical.com/p/4qB3D8DZkk/)

juju add-model keystone-frontend
juju deploy (https://pastebin.canonical.com/p/VWWgVG5cy7/)

juju dashboard
click models
...breakage

**Comment by hatched** [comment]
Thanks for filing this issue @mitechie, great repro steps!

The issue is that the topology is trying to draw a relation to an application in the 'consuming' model `keystone-frontend` that doesn't exist.

<img width="1222" alt="Screen Shot 2020-05-28 at 7 47 17 PM" src="https://user-images.githubusercontent.com/532033/83212239-55de2700-a11c-11ea-8281-ca1b7fa7a648.png">

There are a number of tasks to fully support cross model relations but we should be able to at least prevent the application from breaking until the time when those other tasks can be completed.
