### ISSUE TITLE
Update controller page pie chart design

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#565]
![Screen Shot 2020-06-17 at 9.53.42 AM.png](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/40fb51e0-5541-4a4a-a054-21d8de7b8443)

https://app.zeplin.io/project/5d2dfd8e5b67f14c5e1d2aef/screen/5defb971bac4ceb0d5bca38d

**Comment by cristinadresch** [comment]
@spencerbygraves can you add the latest designs you worked on here pls. I added next milestone to this, but maybe I should put the current one. Just let me know

**Comment by spencerbygraves** [comment]
I've tried a new layout for the data suggested by @cassiocassio. Currently we have 3 graphs but if we add another it will be a squeeze at 1440px due to the extra padding needed.

![image](https://user-images.githubusercontent.com/9105999/86365721-c9baa480-bc71-11ea-9894-acc9722d592a.png)

**3 graphs 1440px**

![image](https://user-images.githubusercontent.com/9105999/86365400-629cf000-bc71-11ea-9aef-72b34eaea155.png)

**4 graphs 1440px**

![image](https://user-images.githubusercontent.com/9105999/86365520-85c79f80-bc71-11ea-9758-cd729e5a90e1.png)

**Different graph style**

Could tie in with graphs elsewhere.

![image](https://user-images.githubusercontent.com/9105999/86365593-9ed05080-bc71-11ea-85b0-02c2b9b4ca7b.png)

**Comment by cristinadresch** [comment]
@spencerbygraves should this be in review?

**Comment by hatched** [comment]
If we update the issue to be only design investigation related... but it was originally to implement the original design which hasn't yet been completed. 

I think we need to investigate these alternative charts, the pie charts kind of break down on smaller widths.

**Comment by spencerbygraves** [comment]
I'm just looking at alternative graphs, but aligning them to right aligned text that grows to the left is tricky :thinking:

**Comment by spencerbygraves** [comment]
I've tried the coloured dots in the middle after @hatched's suggestion.

![image](https://user-images.githubusercontent.com/9105999/87054796-74dfd680-c1fb-11ea-9276-8a8e51623ccf.png)

**Comment by clagom** [comment]
To complicate things up, we also have the CTA to register a controller. I think we need a quick session on this page, it's getting a bit confusing to be honest will all of you :) @cristinadresch something to schedule for next week?

**Comment by hatched** [comment]
being a bit picky but I'd probably center the dot between the numbers and descriptor but I like it :D

It is getting a bit busy though I agree.

**Comment by spencerbygraves** [comment]
@cristinadresch I think we can revert this back to a dev issue, now that @hatched is updating the current page as discussed yesterday. We wont have any new graph designs this iteration.

I've left some comments on Zeplin [here](https://app.zeplin.io/project/5d2dfd8e5b67f14c5e1d2aef/dashboard?seid=5f0ec75c7908918e827b19ee).
