### ISSUE TITLE
Unable to close sidebar in model details page

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/jaas-dashboard#719]
**Describe the bug**

From within the model details page, hover over the sidebar then click the user name in the bottom. It'll pop up, then down again. If you click it again it'll open but then you won't be able to close the sidebar again.

**To Reproduce**
1. Go to the model details page and hover over the sidebar
2. Click your username, it'll bounce.
3. Click it again to open it.
4. Click away from the sidebar, it'll stick around.

**Expected behavior**
It should close when not hovered.

**Screenshots**

![sidenav-bug.gif](https://images.zenhubusercontent.com/5bf56fa65f3ffb2e1680062c/dd5b111f-0a27-4e00-bfa8-4ce9f0b92fff)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 81.0.2

**Comment by barrymcgee** [comment]
This is because;

- The sidebar will open either when hovered over or when anything within it has focus
- When you click 'Settings' within sidebar, you are both hovered over it and an item within it has focus - both conditionals are true.
- However when you hover off the sidebar, only one conditional is false as the focus does not change as focus does not and should not track hover.

These appear to me to be two irreconcilable requirements - I can't remove the focus whenever the sidebar is not hovered as that will breaks keyboard navigation.

In my opinion, the action here is to hasten the move to the Vanilla pattern where we remove this auto collapse feature entirely and instead allow the user to toggle it manually.
