### ISSUE TITLE
Cannot read property 'isRedirectionError' of undefined

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#767]
Intermittently, I'm seeing their error appear locally:

<img width="1155" alt="Screenshot 2020-11-24 at 14 06 50" src="https://user-images.githubusercontent.com/505570/100111210-c49b0380-2e65-11eb-9cf5-3ad7d7a4bf3d.png">

Stack trace in compiled code:

```
> 631 |   if (!juju.isRedirectionError(error)) 
^632 |     reject(error);
  633 |   } // Redirect to the real model.
```

**Comment by barrymcgee** [comment]
@hatch It looks like the error above is coming for [here](https://github.com/juju/js-libjuju/blob/488dc4c4e6229d8ba8b630e4343327fde3b73fe7/api/client.ts#L158) and the fix is to check for `juju` before calling `isRedirectionError`?

As a wider question - why is the dashboard even going through this process on every rerender - should login not be cached?

**Comment by hatched** [comment]
I can't see it going through this on every re-render, it will go through it every time it attempts to connect to the models to pull down the statuses, which will be quite often.

The problem here is that the connection is failing, either by not being able to connect or by some other means which would have been in the browser console not in the CRA popup so I don't know exactly what caused the failure. However the real problem is that the code that is in the catch block assumes that that connection will always complete successfully OR that it'll be returned an instance of the `Client` class. 

The fix is to handle this eventuality in the catch block appropriately. I'll address this this week.

**Comment by anthonydillon** [comment]
Can you get me and Barry permission on the project? It's a relatively simple fix and would be good if we could propose it.

**Comment by barrymcgee** [comment]
Sentry issue: [JUJU-DASHBOARD-64](https://sentry.is.canonical.com/canonical/juju-dashboard/issues/13397/?referrer=github_plugin)
