### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#786]
https://sentry.is.canonical.com/canonical/juju-dashboard/issues/10734/?referrer=github_plugin

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
  at onSuccess (../node_modules/@canonical/macaroon-bakery/index.js:250:39)
  at callback (../node_modules/@canonical/macaroon-bakery/index.js:386:7)
  at handler (../node_modules/@canonical/macaroon-bakery/index.js:593:7)
```

**Comment by barrymcgee** [comment]
Sentry has marked this as resolved due to inactivity

**Comment by mMohamed451** [comment]
how did you solve this issue? 
ERROR SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by hatched** [comment]
Typically this is caused by the request to get the authentication macaroon being blocked by an extension or the request timing out. Check to make sure you are logging into Ubuntu Single Sign On in a reasonable time frame in the new tab that opens and that you don't have any extensions blocking requests to `api.jujucharms.com` or `jimm.jujucharms.com`.

This is all assuming you're getting this on `jaas.ai/models`. If this isn't the case I'll need more information about your setup.
