### ISSUE TITLE
There is a flash of login screen when refreshing UI

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/jaas-dashboard#79]
See example: https://cl.ly/954187927ca2

**Comment by hatched** [comment]
This is happening because the UI renders while the application is initializing and the selector for determining when the user is logged in is a very trivial check for the controller connection and bakery instance. To fix this we need to:
- Add a selector to determine when the application is 'initializing'.
- Update the `login` component to show an 'initializing' UI before it can show the 'login' UI.

**Comment by anthonydillon** [comment]
I would suggest displaying the grid layout of the application as the application inits. Then either display the login model or hide the overlay and load content.

RBAC example: https://app.zeplin.io/project/5bfc141b92d01e7ea2b72146/screen/5c07e5edd206de5ee1db6673
